// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CheckCookies struct {
	User  string `json:"user"`
	Check string `json:"check"`
}

type Cookies struct {
	PtKey  string  `json:"pt_key"`
	PtPin  string  `json:"pt_pin"`
	WsKey  *string `json:"ws_key"`
	Remark *string `json:"remark"`
}
