name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        run: |
          sudo apt-get -y install upx
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          CGO_ENABLED=0 go build -o app -tags=jsoniter
          upx app

      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: 'app,config.toml'
          target: ${{ secrets.REMOTE_TARGET }}

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: ${{ secrets.AFTER_COMMAND }}